### ISSUE TITLE
Chrome44で new AudioContext() を7回以上呼ばれるとエラー

### ISSUE THREAD

**Issue by noblejasper** [CyberAgent/boombox.js#21]
boomboxを複数箇所で呼んでいる事が要因だと思うのですが、
下記のエラーが出てしまいます。

```
Failed to construct "AudioContext': number of hardware contexts reached maximum (6).
```

こちらはboombox側で回避する事は難しいでしょうか？

今手元の状況としては、

1. 1つのタブで使用しているサイトを開く
2. そのタブ内から_blankで別タブにリンク先を開く
3. 2つのタブを合わせて7回以上叩かれているとエラーが出てしまいます

お手数おかけしますがご調査頂けますととても助かります！

**Comment by Layzie** [comment]
@noblejasper 

こちらはChorme(Blink)のAudioContextの仕様のようなので、エラーの回避は厳しいかと思います。

[こちらのL22](https://chromium.googlesource.com/chromium/blink/+/master/Source/modules/webaudio/AudioContext.cpp)で6回までに制限されています。

一応、`AudioContext.close()` メソッドを呼んで破棄するとエラー自体は無くなるようですが、GCに乗るのに時間差がありすぐに破棄されないというのは[既知の問題](https://code.google.com/p/chromium/issues/detail?id=308784#c16)のようです。
